### ISSUE TITLE
輸出雙月合理調整值

### ISSUE THREAD

**Issue by y12studio** [kiang/taipower#1]
各縣市村里用電資訊records.csv調整為合理預估值後輸出另一份csv供後端消費方便輸出報告，舉下例圖將原八月值與七月平均兩個月數值一致，或是依上升趨勢內插分配調整。

![upload-xxx](https://cloud.githubusercontent.com/assets/1840874/16544281/b2189c10-4132-11e6-923e-0f855156afb4.png)

參考圖
 https://docs.google.com/spreadsheets/d/13aH8TrBGuJTDx61lRhYdNxT0SIBWcNsgwbpJrpXnSWQ/pubchart?oid=1778019287&format=interactive

三里電力圖與Google試算圖表 
 https://gist.github.com/y12studio/19a7e7c93c3281b5855a883dc4f80b6d

**Comment by kiang** [comment]
目前還沒具體處理，兩個月的資料合併應該是符合實務的作法，但因為合併動作不難所以清理資料時沒有特別加入，盡量保留原始按月型態資料去修正錯誤。但其實也有很多只是個人的猜測，因為沒有原始資料可以驗證，希望資料提供方願意從原始資料進行修正

**Comment by y12studio** [comment]
平均與加權調整比較供參考，先關掉後續視原始資料輸出狀態再來處理。

![upload-xxx](https://cloud.githubusercontent.com/assets/1840874/16574368/b4874440-42b0-11e6-9933-659bbff1a20c.png)

比較圖 
 https://docs.google.com/spreadsheets/d/1yGr5_njWlWcPnRgIdtd7RILThs-fHdedVERIUigPMNg/pubchart?oid=1778019287&format=interactive

y12js/odtw/taipower 
 https://github.com/y12studio/y12js/tree/master/odtw/taipower
